### ISSUE TITLE
Unable to call server.about.xxx from ssb-client

### ISSUE THREAD

**Issue by SyarifZapata** [ssbc/ssb-about#3]
I run ssb-server which uses ssb-about as a plugin, 
on the client side i want to pull from the `server.about.socialValueStream` but i get an error message: server.about is undefined. 

```
Client({port:8008}, function (err, server) {

  pull(
   server.about.socialValueStream({ key: 'avatar', dest:  '@3r4+IyB5NVl2in6...... }), pull.drain(avatar => {
                  console.log(avatar)
     })
   )
}
```

is there any other way i can pull about-data from the client side? thanks for your help

**Comment by AljoschaMeyer** [comment]
@SyarifZapata I've randomly stumbled over this issue just now. Is this still open?

As far as I know, the problem here is that the client side doesn't know about the plugin. At some point, your client code should read in a `manifest` file, or get hold of some sort of manifest object. This might happen implicitly, loading it from `~/.ssb/manifest.json`. the manifest tells the client object which methods the server exposes. I'm sorry I can't give you more details on this, my knowledge of this comes from a short pairing-session with @mixmix. But I'm fairly confident that this is the problem you are encountering.

We really need some documentation on how to actually use plugins...

*edit*: see also https://github.com/ssbc/ssb-about/blob/single-get/example.js#L26
*edit2*: By now I expect you understand why I advised you to stay as far away from ssb as possible for now =/

**Comment by mixmix** [comment]
Your main problem is probably `ssb-client` needs a lot more detail than just `{ port }`

My recommendation would be to do this : 

```js
// server.js 
const Server = require('ssb-server')
const Config = require('ssb-config/inject')
const fs = require('fs')
const path = require('path')

Server
  .use(require('ssb-server/plugins/master'))
  .user(require('ssb-about'))

const config = Config() // you can read about other opts you can put in here
const server = Server(config)

const manifest = server.getManifest()  // I think this is the method, that or just `server.manifest` .. 
fs.writeFileSync(path.join(config.path, JSON.stringify(manifest.json)))
// this puts a copy of the manifest in the path of your ssb identity, which is one place ssb-client will check for it
```

```js
// client.js

const Client = require('ssb-client')
const Config = require('ssb-config/inject')

const config = Config()

Client(config.keys, config, (err, server) => {
    pull(
      server.about.socialValueStream({ key: 'avatar', dest:  '@3r4+IyB5NVl2in6......' }),
      pull.drain(avatar => {
        console.log(avatar)
      })
    )
}) 
```

**Comment by mixmix** [comment]
I'm going to assume that fixes it, and close this for now. Please at-mention us if I'm wrong.
